# D-Tale EDA(Exploratory Data Analysis)
1. D-Tale is a powerful EDA tool that lets you interactively explore your Pandas DataFrame in a web-style interface â€” directly from Jupyter or Google Colab.

2. ðŸ§  What You Can Do with D-Tale:
   1. Sort/filter/search data

   2.  Create histograms, bar charts, box plots

   3. View correlations

   4. Clean missing data

   5. Export cleaned data

In [15]:
!pip install dtale

Requirement already satisfied: dtale in c:\users\vikram\anaconda3\lib\site-packages (3.17.0)
Requirement already satisfied: dash-daq<=0.5.0 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.5.0)
Requirement already satisfied: future>=0.14.0 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.0.0)
Requirement already satisfied: missingno in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.5.2)
Requirement already satisfied: pandas in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2.2.2)
Requirement already satisfied: squarify in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.4.4)
Requirement already satisfied: strsimpy in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.2.1)
Requirement already satisfied: six in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: xlrd in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (4.12.3)
Requirement already satisfied: certifi in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2025.1.31)
Requirement already satisfied: dash-bootstrap-components<=1.7.1 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.7.1)
Requirement already satisfied: lz4 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (4.3.2)
Requirement already satisfied: cycler in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.11.0)
Requirement already satisfied: dash<=2.18.2 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2.18.2)
Requirement already satisfied: seaborn in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.13.2)
Requirement already satisfied: werkzeug in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (3.0.3)
Requirement already satisfied: Flask-Compress in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.17)
Requirement already satisfied: scikit-learn in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.5.1)
Requirement already satisfied: statsmodels in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.14.2)
Requirement already satisfied: networkx in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (3.3)
Requirement already satisfied: numpy in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.26.4)
Requirement already satisfied: openpyxl!=3.2.0b1 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (3.1.5)
Requirement already satisfied: xarray in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2023.6.0)
Requirement already satisfied: scipy!=1.12.0rc1,!=1.14.0,!=1.14.0rc1,!=1.14.0rc2 in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.13.1)
Requirement already satisfied: et-xmlfile in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (1.1.0)
Requirement already satisfied: plotly in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (5.24.1)
Requirement already satisfied: Flask in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (3.0.3)
Requirement already satisfied: itsdangerous in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2.2.0)
Requirement already satisfied: requests in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (2.32.3)
Requirement already satisfied: kaleido in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (0.2.1)
Requirement already satisfied: matplotlib in c:\users\vikram\anaconda3\lib\site-packages (from dtale) (3.9.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\vikram\anaconda3\lib\site-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.5)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (5.0.0)
Requirement already satisfied: importlib-metadata in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (7.0.1)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (4.11.0)
Requirement already satisfied: retrying in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (1.6.0)
Requirement already satisfied: setuptools in c:\users\vikram\anaconda3\lib\site-packages (from dash<=2.18.2->dtale) (75.1.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\vikram\anaconda3\lib\site-packages (from Flask->dtale) (3.1.4)
Requirement already satisfied: click>=8.1.3 in c:\users\vikram\anaconda3\lib\site-packages (from Flask->dtale) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\users\vikram\anaconda3\lib\site-packages (from Flask->dtale) (1.6.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\vikram\anaconda3\lib\site-packages (from plotly->dtale) (8.2.3)
Requirement already satisfied: packaging in c:\users\vikram\anaconda3\lib\site-packages (from plotly->dtale) (24.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\vikram\anaconda3\lib\site-packages (from werkzeug->dtale) (2.1.3)
Requirement already satisfied: brotli in c:\users\vikram\anaconda3\lib\site-packages (from Flask-Compress->dtale) (1.0.9)
Requirement already satisfied: zstandard in c:\users\vikram\anaconda3\lib\site-packages (from Flask-Compress->dtale) (0.23.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (1.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vikram\anaconda3\lib\site-packages (from matplotlib->dtale) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vikram\anaconda3\lib\site-packages (from pandas->dtale) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vikram\anaconda3\lib\site-packages (from pandas->dtale) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\vikram\anaconda3\lib\site-packages (from requests->dtale) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vikram\anaconda3\lib\site-packages (from requests->dtale) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\vikram\anaconda3\lib\site-packages (from requests->dtale) (2.2.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vikram\anaconda3\lib\site-packages (from scikit-learn->dtale) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vikram\anaconda3\lib\site-packages (from scikit-learn->dtale) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\vikram\anaconda3\lib\site-packages (from statsmodels->dtale) (0.5.6)
Requirement already satisfied: colorama in c:\users\vikram\anaconda3\lib\site-packages (from click>=8.1.3->Flask->dtale) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\vikram\anaconda3\lib\site-packages (from importlib-metadata->dash<=2.18.2->dtale) (3.17.0)

In [4]:
import pandas as pd
import dtale
import seaborn as sns

In [8]:
# Load Titanic dataset
df = sns.load_dataset("titanic")

In [10]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [21]:
# Start D-Tale

dtale.show(df)

In [ ]:

d = dtale.show(df)
d.open_browser()  # Opens D-Tale in your browser